### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by wklken** [wklken/gorequest#16]
## DONE

- [x] https://github.com/parnurzeal/gorequest/issues/113  https://github.com/wklken/gorequest/pull/23
- [x] https://github.com/parnurzeal/gorequest/issues/217
- [x] https://github.com/parnurzeal/gorequest/issues/204
- sendfile:
    - [x] MimeType https://github.com/parnurzeal/gorequest/pull/213/files
    - [x] enable custom Content-Type for SendFile https://github.com/parnurzeal/gorequest/pull/170 https://github.com/parnurzeal/gorequest/issues/208
- [x] timeout detail https://github.com/parnurzeal/gorequest/pull/183/files
- [x] gzip support: https://github.com/parnurzeal/gorequest/issues/195   see https://go.dev/src/net/http/transport.go#L190

### high

- sendfile:
    - [ ] filename always be `file` https://github.com/parnurzeal/gorequest/issues/219 https://github.com/parnurzeal/gorequest/issues/132 https://github.com/parnurzeal/gorequest/issues/245
- [ ] support digest https://github.com/parnurzeal/gorequest/issues/247  /  https://github.com/parnurzeal/gorequest/issues/206
- [ ] logger, maybe add a better interface https://github.com/parnurzeal/gorequest/issues/232
- [ ] https://github.com/parnurzeal/gorequest/issues/251 https://stackoverflow.com/questions/26050380/go-tracking-post-request-progress

### new features

- [x] use https://github.com/json-iterator/go
- [ ] use httpbin.org in docs and examples
- [ ] use ginkgo
- [ ] enhance debug / print 
- [ ] otel support
- [ ] metrics and slow logs
- [ ] return errors(an array), add more functions to get size/firstOne/hasError/error handler
- [ ] add metrics support
- [ ] add slow log/error log support

### others

- [ ] Trim the BOM in EndStruct() https://github.com/parnurzeal/gorequest/pull/179
- [ ] fasthttp alternative? 
    - https://github.com/parnurzeal/gorequest/issues/153
    - https://github.com/parnurzeal/gorequest/issues/110
    - https://github.com/parnurzeal/gorequest/issues/71
- [ ] docs and faqs
    - [ ] https://github.com/parnurzeal/gorequest/issues/152
    - [ ] https://github.com/parnurzeal/gorequest/issues/145
    - [ ] https://github.com/parnurzeal/gorequest/issues/125
    - [ ] https://github.com/parnurzeal/gorequest/issues/117
    - [ ] https://github.com/parnurzeal/gorequest/issues/112
    - [ ] https://github.com/parnurzeal/gorequest/pull/171/files
- [ ] add examples/*.go
    - [ ] https://github.com/parnurzeal/gorequest/issues/152
    - [ ] https://github.com/parnurzeal/gorequest/issues/125
    - [ ] https://github.com/parnurzeal/gorequest/issues/117
    - [ ] https://github.com/parnurzeal/gorequest/issues/112
    - [ ] https://github.com/parnurzeal/gorequest/pull/171/files
- [ ] https://github.com/parnurzeal/gorequest/issues/144
- [ ] https://github.com/parnurzeal/gorequest/issues/262
- [ ] question: https://github.com/parnurzeal/gorequest/issues/142 https://github.com/parnurzeal/gorequest/issues/141  https://github.com/parnurzeal/gorequest/issues/45

**Comment by wklken** [comment]
## gzip

no need to support.
1. now support: `DisableCompression()`
2. if not set, the gzip response will be ungzipped
