### ISSUE TITLE
TODO LIst before v1.0.0

### ISSUE THREAD

**Issue by wklken** [wklken/gorequest#5]
## DONE

- [x] typo: https://github.com/parnurzeal/gorequest/issues/177
- [x] use bytes/string conv func
- [x] add context? https://github.com/parnurzeal/gorequest/pull/227  https://github.com/parnurzeal/gorequest/pull/218  https://github.com/parnurzeal/gorequest/issues/255
- [x] https://github.com/parnurzeal/gorequest/issues/264
- [x] https://github.com/parnurzeal/gorequest/issues/265
- [x] https://github.com/parnurzeal/gorequest/issues/220
- [x] https://github.com/parnurzeal/gorequest/issues/205
- [x] https://github.com/parnurzeal/gorequest/issues/138
- [x] https://github.com/parnurzeal/gorequest/issues/253
- [x] https://github.com/parnurzeal/gorequest/issues/214
- [x] https://github.com/parnurzeal/gorequest/issues/207
- [x] https://github.com/parnurzeal/gorequest/issues/250
- [x] https://github.com/parnurzeal/gorequest/issues/131
- [x] retry
    - https://github.com/parnurzeal/gorequest/issues/254
    - https://github.com/parnurzeal/gorequest/issues/168
    - https://github.com/parnurzeal/gorequest/pull/203/files
    - https://github.com/parnurzeal/gorequest/pull/190/files
- [x] https://github.com/parnurzeal/gorequest/issues/11
- [x] set headers? https://github.com/parnurzeal/gorequest/pull/231/files

## TODO

- [ ] https://github.com/parnurzeal/gorequest/pull/170

## High

- [ ] use https://github.com/json-iterator/go
- [ ] use httpbin.org in docs and examples
- [ ] use ginkgo
- [ ] enhance debug / print 
- [ ] otel support
- [ ] metrics and slow logs
- [ ] enable custom Content-Type for SendFile https://github.com/parnurzeal/gorequest/pull/213/files
- [ ] timeout detail https://github.com/parnurzeal/gorequest/pull/183/files
- [ ] Trim the BOM in EndStruct() https://github.com/parnurzeal/gorequest/pull/179
- [ ] https://github.com/parnurzeal/gorequest/issues/219
- [ ] https://github.com/parnurzeal/gorequest/issues/143
- [ ] https://github.com/parnurzeal/gorequest/issues/132
- [ ] https://github.com/parnurzeal/gorequest/issues/75

## Medium

- [ ] https://github.com/parnurzeal/gorequest/issues/262
- [ ] https://github.com/parnurzeal/gorequest/issues/256
- [ ] support digest https://github.com/parnurzeal/gorequest/issues/247  /  https://github.com/parnurzeal/gorequest/issues/206
- [ ] https://github.com/parnurzeal/gorequest/issues/245
- [ ] logger, maybe add a better interface https://github.com/parnurzeal/gorequest/issues/232
- [ ] https://github.com/parnurzeal/gorequest/issues/222
- [ ] https://github.com/parnurzeal/gorequest/issues/208
- [ ] https://github.com/parnurzeal/gorequest/issues/204
- [ ] gzip support: https://github.com/parnurzeal/gorequest/issues/195
- [ ] fasthttp alternative? 
    - https://github.com/parnurzeal/gorequest/issues/153
    - https://github.com/parnurzeal/gorequest/issues/110
    - https://github.com/parnurzeal/gorequest/issues/71
- [ ] docs and faqs
    - [ ] https://github.com/parnurzeal/gorequest/issues/152
    - [ ] https://github.com/parnurzeal/gorequest/issues/145
    - [ ] https://github.com/parnurzeal/gorequest/issues/125
    - [ ] https://github.com/parnurzeal/gorequest/issues/117
    - [ ] https://github.com/parnurzeal/gorequest/issues/112
    - [x] https://github.com/parnurzeal/gorequest/issues/159
    - [ ] https://github.com/parnurzeal/gorequest/pull/171/files
- [ ] add examples/*.go
    - [x] https://github.com/parnurzeal/gorequest/issues/145
    - [ ] https://github.com/parnurzeal/gorequest/issues/152
    - [ ] https://github.com/parnurzeal/gorequest/issues/125
    - [ ] https://github.com/parnurzeal/gorequest/issues/117
    - [ ] https://github.com/parnurzeal/gorequest/issues/112
    - [x] https://github.com/parnurzeal/gorequest/issues/159
    - [x] https://github.com/parnurzeal/gorequest/pull/171/files
- [ ] return errors(an array), add more functions to get size/firstOne/hasError/error handler
- [ ] add metrics support
- [ ] add slow log/error log support
- [ ] https  https://github.com/parnurzeal/gorequest/issues/144
- [ ] https://github.com/parnurzeal/gorequest/issues/113
- [ ] concurrent https://github.com/parnurzeal/gorequest/issues/27

## Low

- [ ] https://github.com/parnurzeal/gorequest/issues/261
- [ ] https://github.com/parnurzeal/gorequest/issues/260
- [ ] https://github.com/parnurzeal/gorequest/issues/251
- [ ] https://github.com/parnurzeal/gorequest/issues/217
- [ ] https://github.com/parnurzeal/gorequest/issues/192
- [ ] question: https://github.com/parnurzeal/gorequest/issues/142 https://github.com/parnurzeal/gorequest/issues/141  https://github.com/parnurzeal/gorequest/issues/45
- [ ] https://github.com/parnurzeal/gorequest/issues/77

## Won't Fix

- [x] https://github.com/parnurzeal/gorequest/issues/182
- [x] fork and make some changes => https://github.com/parnurzeal/gorequest/issues/173  https://github.com/parnurzeal/gorequest/issues/221

**Comment by wklken** [comment]
## CR Required

- bug: send `{}`: https://github.com/wklken/gorequest/pull/6
- bug: converting query keys to lower case: https://github.com/wklken/gorequest/pull/7
- bug: query with int64 will lose accuracy: https://github.com/wklken/gorequest/pull/8
- add: wrap the EndStruct error if json decode fail: https://github.com/wklken/gorequest/pull/9
- add docs, string bytes conv: https://github.com/wklken/gorequest/pull/10
- fix: get not set s.TargetType to "json" https://github.com/wklken/gorequest/pull/11
- add context support: https://github.com/wklken/gorequest/pull/12
- fix retry if errors: https://github.com/wklken/gorequest/pull/13
- add: SetHeaders: https://github.com/wklken/gorequest/pull/14
-

**Comment by wklken** [comment]
move to https://github.com/wklken/gorequest/issues/16

close
